spring:
  datasource:
    url: jdbc:h2:./data/fleet;DB_CLOSE_DELAY=-1;init=CREATE SCHEMA IF NOT EXISTS fleet;
    username: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
    hibernate.ddl-auto: none
    show-sql: true

flyway:
  baseline-on-migrate: true
  schemas: fleet
  url: jdbc:h2:./data/fleet
  locations: classpath:db/migration
